[package]
name = "cloakroom_model"
version = "0.1.0"
authors = ["Philip Mortimer <mortimer_philip@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
